{
  "hash": "6a2f0cc4c7192ccfda6b6adcda724b61",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Statistical Learning\"\nauthor: \"Dania Machlab\"\ndescription: \"Linear Models\"\nformat: html\n---\n\n\n::: {.cell}\n\n:::\n\n\n## Overview\n\n### Learning outcomes\n\n- understand what a linear model is\n- understand the different flavors of linear regression and what differenciates them\n- understand variance-bias trade off and colinearity in regression\n- be able to assess what linear regression fits best to learn what you need from your data\n\nNote that boxes labeled **Task** will ask you to do follow up anaylses or exploration using what has been demonstrated. We will discuss them and go through them together.\n\n### Linear models\n\n\nLinear models are incredibly useful and powerful in that they allows us to learn something from the data while providing a high degree of interpretability. Given a variable $y$, the model assumes the expected value of $y$ is linear in the inputs $x$.\n\n\n\n### Annotations and vocabulary\n\nWe will refer to the dep var y, x, X.., e, epsilon etc\n\nassumptions: indep observations, n > p, error normal with mean 0, linear relationship no collinearity\n\n### The data sets\n\nexplain about advertising and credit data sets. and Auto\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Set to the desired working directory (you may change this to suit your wdir)\nwdir <- \"~/GitHub/raukr-2026/labs/statistics\"\nsetwd(wdir)\n\n## Download the dataset\ndownload.file(url = \"https://www.statlearning.com/s/Advertising.csv\", \n              destfile = file.path(wdir, \"assets\", \"Advertising.csv\"))\n\n## Read in the data \nadvertisingData <- read.csv(file = \"assets/Advertising.csv\", \n                            header = TRUE, \n                            row.names = 1)\nstr(advertisingData)\nhead(advertisingData)\nsummary(advertisingData)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t200 obs. of  4 variables:\n $ TV       : num  230.1 44.5 17.2 151.5 180.8 ...\n $ radio    : num  37.8 39.3 45.9 41.3 10.8 48.9 32.8 19.6 2.1 2.6 ...\n $ newspaper: num  69.2 45.1 69.3 58.5 58.4 75 23.5 11.6 1 21.2 ...\n $ sales    : num  22.1 10.4 9.3 18.5 12.9 7.2 11.8 13.2 4.8 10.6 ...\n```\n\n\n:::\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|    TV| radio| newspaper| sales|\n|-----:|-----:|---------:|-----:|\n| 230.1|  37.8|      69.2|  22.1|\n|  44.5|  39.3|      45.1|  10.4|\n|  17.2|  45.9|      69.3|   9.3|\n| 151.5|  41.3|      58.5|  18.5|\n| 180.8|  10.8|      58.4|  12.9|\n|   8.7|  48.9|      75.0|   7.2|\n\n</div>\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       TV             radio          newspaper          sales      \n Min.   :  0.70   Min.   : 0.000   Min.   :  0.30   Min.   : 1.60  \n 1st Qu.: 74.38   1st Qu.: 9.975   1st Qu.: 12.75   1st Qu.:10.38  \n Median :149.75   Median :22.900   Median : 25.75   Median :12.90  \n Mean   :147.04   Mean   :23.264   Mean   : 30.55   Mean   :14.02  \n 3rd Qu.:218.82   3rd Qu.:36.525   3rd Qu.: 45.10   3rd Qu.:17.40  \n Max.   :296.40   Max.   :49.600   Max.   :114.00   Max.   :27.00  \n```\n\n\n:::\n:::\n\n\n\n## Simple linear regression\n\nAs the name implies, a simple linear regression predicts a quantitative response $y$ on the basis of a single predictor $x$ and assumes an approximately linear relationship between $x$ and $y$. Mathematically, we can write this linear relationship as $$y = \\beta_0 + \\beta_1x + \\epsilon$$ where $\\beta_0$ and $\\beta_1$ are the intercept term and the coefficient for $x$ respectively. The error term $\\epsilon$ captures the noise or lack of fit to the linear equation.\n\nLet us use the advertising data set, to see if we can learn something about the relationship between TV advertising and sales. In other words, we are estimating the beta coefficients in the following equation: $sales = \\beta_0 + \\beta_1TV + \\epsilon$.\n\nLet us have a first look at the sales vs TV relationship in the data. Visually, we can see some kind of linear relationship and that sales increases with increasing TV advertising budget. Is there anything else you notice about the spread of the data?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(advertisingData, aes(x = TV, y = sales)) + \n    geom_point() + \n    theme_bw()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nLet's estimate the beta coefficients and learn the exact linear function capturing this relationship.\n\n::: {.cell}\n\n```{.r .cell-code}\n## Fit linear model\nsimpleLinearFit <- lm(sales ~ TV, data = advertisingData) \nsimpleLinearFit\nnames(simpleLinearFit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sales ~ TV, data = advertisingData)\n\nCoefficients:\n(Intercept)           TV  \n    7.03259      0.04754  \n\n [1] \"coefficients\"  \"residuals\"     \"effects\"       \"rank\"         \n [5] \"fitted.values\" \"assign\"        \"qr\"            \"df.residual\"  \n [9] \"xlevels\"       \"call\"          \"terms\"         \"model\"        \n```\n\n\n:::\n:::\n\n\n::: {.callout-note appearance=\"simple\" icon=false}\n## Task\nExplore the `simpleLinearFit` object and what it contains. You can make use of the following methods: `str()`, `class()`, `names()` and the `$` sign to access slots. You can also refer to the help page of the `lm()` function to see what it returns. Do you get the same values if you compare the `residuals` from the `simpleLinearFit` object to the difference between the sales values and the `fitted.values` in the `simpleLinearFit` object? Plot the distribution of the residuals. Is it approximately normal?\n:::\n\nLet's plot the linear fit on our original scatter plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## prepare to plot\ndf <- do.call(cbind, list(advertisingData, \n                          residual = simpleLinearFit$residuals, \n                          predictedSales = simpleLinearFit$fitted.values))\nbeta0 <- simpleLinearFit$coefficients[\"(Intercept)\"]\nbeta1 <- simpleLinearFit$coefficients[\"TV\"]\n\n## plot\np1 <- ggplot(df, aes(x = TV, y = sales)) + \n    geom_point() +\n    geom_abline(intercept = beta0, slope = beta1, color = \"firebrick\") + \n    theme_bw()\n\np2 <- p1 + \n    geom_segment(aes(x = TV, xend = TV, y = sales, yend = predictedSales),\n                 color = \"steelblue\")\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n\nThe red line is the linear fit and we can visualize the residuals in blue, which show the difference between predicted and observed sales values. Recall that for each observation $i$, the residual $e_i=y_i-\\hat{y_i}$. \n\n::: {.callout-note appearance=\"simple\" icon=false}\n## Task\nPlot the distribution of the residuals. Is it approximately normal?\n:::\n\nNow that we have our fit, how do we interpret the values of the beta coefficients and what can we communicate back to our clients? $\\beta_0$ is the intercept term, and shows the expected value of $y$ when $x=0$. The slope, $\\beta_1$, shows the average increase in $y$ associated with a one-unit increase in $x$. In our example, $\\beta_0$ has a value of 7.0326 and $\\beta_1$ a value of 0.0475. That means that an additional \\$1000 spent on TV advertising is associated with selling approximately 47.5 extra units of the product.\n\n::: {.callout-note appearance=\"simple\" icon=false}\n## Task\nPick either one of the other two advertising budgets, newspaper or radio, and repeat this exercise. What are you expecting based on the scatter plots before doing any fit? Is there a positive relationship to sales, and to what extent? Fit a line and interpret the coefficients. Can you say something about how well the fit captures the trend in the data?\n:::\n\n\n### Assessing the quality of the fit\n\nWe will explore two measures that allow us to assess the quality of the linear regression fit: the residual standard error (RSE) and the $R^2$ statistic.\n\nRecall that we can't perfectly predict $y$ from $x$ and that there is an associated residual $e$ for each observation showing how much we have deviated from the line. The RSE roughly represents the average amount of deviation from this line, as reflected in its formula: $RSE=\\sqrt{\\frac{1}{n-2}RSS}$. Let's have a look at the RSE value in our example. Not that here we have $n-2$ since we have 2 coefficients.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(simpleLinearFit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sales ~ TV, data = advertisingData)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8.3860 -1.9545 -0.1913  2.0671  7.2124 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 7.032594   0.457843   15.36   <2e-16 ***\nTV          0.047537   0.002691   17.67   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.259 on 198 degrees of freedom\nMultiple R-squared:  0.6119,\tAdjusted R-squared:  0.6099 \nF-statistic: 312.1 on 1 and 198 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe RSE has a value of 3.26. The observed sales deviate from the true regression line by about 3,260 units on average (since the sales is in thousands of units). Is this something we can live with? What is the mean value of sales in our data set?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## mean sales (in thousdands of units)\nmean(advertisingData$sales)\n\n## percentage error\nsummary(simpleLinearFit)$sigma / mean(advertisingData$sales) * 100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 14.0225\n[1] 23.23877\n```\n\n\n:::\n:::\n\n\nThe size of the RSE value will reflect how poorly the model fits the data. However, the RSE is measured in units of $y$ and it is not always clear what a good value should be. The $R^2$ statistic on the other hand represents the proportion of variance explained, meaning it will always have a value between 0 and 1: $R^2=\\frac{TSS-RSS}{TSS}$ where $TSS=\\sum(y_i-\\bar{y})^2$. TSS is the **t**otal **s**um of **s**quares and measures the total variance in $y$, whereas the RSS can be thought of as measuring the variability that is left unexplained after doing the regression. The $R^2$ value thus reflects the proportion of variability in $y$ that can be explained using $x$ by performing the regression. In our example, $R^2$ has a value of 0.61, meaning that around two thirds of the variability in sales is explained by a linear regression on TV advertising budget. Even though the $R^2$ is nicely interpretable, it can still be difficult to judge what a good value should look like in practice, particularly in fields where data is generated with a degree of experimental noise such as in biology.\n\n::: callout-note\nNote that in the case of the simple linear regression, the $R^2$ is identical to $Cor(y, \\hat{y})^2$.\n:::\n\n\n\n## Multiple linear regression\n\nNow that we have a good understanding of the simple linear regression with one dependent variable $x$, let's extend this problem by including more predictors (dependent variables). Continuing with the advertising data set, can we say something about which kind of advertising has a bigger impact on sales based on the size of the beta coefficients? With more than one predictor, this form of linear regression is called multiple linear regression and is formulated as follows for $p$ predictors: $y = \\beta_0 + \\beta_1x_1 + \\beta_2x_2 + ... + \\beta_px_p + \\epsilon$.\n\nIn the original advertising data, $sales = \\beta_0 + \\beta_1TV + \\beta_2radio + \\beta_3newspaper + \\epsilon$. As with the simple linear regression, we estimate the beta coefficients to minimize the sum of the squared residuals or the RSS.\n\nWe don't have too many predictors to crowd a pairs plot. Let's look at all combinations of scatter plots and get a feeling for the data. What can we see?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## visualize the data\npairs(advertisingData, pch = 16)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## fit\nmultipleLinearFit <- lm(sales ~ TV + radio + newspaper, \n                        data = advertisingData) \nmultipleLinearFit\n\n## compare to the sales ~ TV fit\nsummary(simpleLinearFit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sales ~ TV + radio + newspaper, data = advertisingData)\n\nCoefficients:\n(Intercept)           TV        radio    newspaper  \n   2.938889     0.045765     0.188530    -0.001037  \n\n\nCall:\nlm(formula = sales ~ TV, data = advertisingData)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8.3860 -1.9545 -0.1913  2.0671  7.2124 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 7.032594   0.457843   15.36   <2e-16 ***\nTV          0.047537   0.002691   17.67   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.259 on 198 degrees of freedom\nMultiple R-squared:  0.6119,\tAdjusted R-squared:  0.6099 \nF-statistic: 312.1 on 1 and 198 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(multipleLinearFit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sales ~ TV + radio + newspaper, data = advertisingData)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8.8277 -0.8908  0.2418  1.1893  2.8292 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  2.938889   0.311908   9.422   <2e-16 ***\nTV           0.045765   0.001395  32.809   <2e-16 ***\nradio        0.188530   0.008611  21.893   <2e-16 ***\nnewspaper   -0.001037   0.005871  -0.177     0.86    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.686 on 196 degrees of freedom\nMultiple R-squared:  0.8972,\tAdjusted R-squared:  0.8956 \nF-statistic: 570.3 on 3 and 196 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nWe interpret $\\beta_j$ as the average effect on $y$ of a one unit increase in $x_j$, holding all other predictors fixed. Spending an additional \\$1,000 on radio advertising is associated with an average increase in around 189 units of additional sales. How to the coefficients for all predictors in the multiple linear regression compare to the coefficients if we were to do a simple linear regression separately per predictor? What do you notice about the newspaper predictor and the (adjusted) $R^2$ values?\n\nThe multiple linear regression allows us to assess the contribution of a predictor in explaining the response vector in context with the other predictors and allows us to assess the relative contributions of each predictor.\n\n\n## Interaction terms\n\nIn our advertising data, we have seen that both the TV and radio are media whose budgets contribute towards explaining the sales and both have (significantly) positive coefficient estimates. But what can we say about their joint contribution towards the sales at the same time? What if each predictor is associated with sales in a different way, and if we were to take them together the beta coefficient for the TV and radio budget would be even bigger? These are questions we currently have, and which we can address by including an interaction term, reflecting the product of the TV and radio predictors. \n\nWe can represent the predictors in a matrix form $X$ called the predictor matrix. The equation $y = \\beta_0 + \\beta_1x_1 + \\beta_2x_2 + ... + \\beta_px_p + \\epsilon$ can be rewritten as $y = \\beta.X + \\epsilon$ where $\\beta$ is the vector of beta coefficients which we are estimating. $X$ includes the intercept term which is a vector of 1s (multiplying 1 by the estimated intercept yields the intercept). In R we can use the `model.matrix()` function to create this matrix (the `lm()` function does this internally).\n\nTo add an interaction term, we can simply add `TV:radio` into the `lm()` function, or we can use `TV*radio` which will expand into `TV + radio + TV:radio`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## create predictor matrix (you may recognize this as the design matrix)\nX <- model.matrix(~ TV + radio + newspaper + TV:radio, \n                  data = advertisingData)\nhead(X)\n\n## linear regression (all ways below work)\n#lm(sales ~ TV + radio + TV:radio + newspaper, data = advertisingData)\n#lm(sales ~ TV*radio + newspaper, data = advertisingData)\nfit <- lm(advertisingData$sales ~ X + 0)\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept)    TV radio newspaper TV:radio\n1           1 230.1  37.8      69.2  8697.78\n2           1  44.5  39.3      45.1  1748.85\n3           1  17.2  45.9      69.3   789.48\n4           1 151.5  41.3      58.5  6256.95\n5           1 180.8  10.8      58.4  1952.64\n6           1   8.7  48.9      75.0   425.43\n\nCall:\nlm(formula = advertisingData$sales ~ X + 0)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-6.2929 -0.3983  0.1811  0.5957  1.5009 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \nX(Intercept) 6.728e+00  2.533e-01  26.561  < 2e-16 ***\nXTV          1.907e-02  1.509e-03  12.633  < 2e-16 ***\nXradio       2.799e-02  9.141e-03   3.062  0.00251 ** \nXnewspaper   1.444e-03  3.295e-03   0.438  0.66169    \nXTV:radio    1.087e-03  5.256e-05  20.686  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.9455 on 195 degrees of freedom\nMultiple R-squared:  0.9961,\tAdjusted R-squared:  0.996 \nF-statistic:  9972 on 5 and 195 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nWhat do you notice about the beta coefficients and the adjusted R-squared?\n\n\n\n## Categorical variables\n\nSo far we have dealt with quantitative values of the predictors. What if we have a qualitative variable for example indicating presence or absence? What happens in the linear fit when such a predictor exists? To illustrate this, we will use another data set, namely the Credit data set, where we have a mixture of quantitative and qualitative variables.\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(Credit)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|  Income| Limit| Rating| Cards| Age| Education|Own |Student |Married |Region | Balance|\n|-------:|-----:|------:|-----:|---:|---------:|:---|:-------|:-------|:------|-------:|\n|  14.891|  3606|    283|     2|  34|        11|No  |No      |Yes     |South  |     333|\n| 106.025|  6645|    483|     3|  82|        15|Yes |Yes     |Yes     |West   |     903|\n| 104.593|  7075|    514|     4|  71|        11|No  |No      |No      |West   |     580|\n| 148.924|  9504|    681|     3|  36|        11|Yes |No      |No      |West   |     964|\n|  55.882|  4897|    357|     2|  68|        16|No  |No      |Yes     |South  |     331|\n|  80.180|  8047|    569|     4|  77|        10|No  |No      |No      |South  |    1151|\n\n</div>\n:::\n:::\n\n\n\nTo illustrate, we will use the balance variable as the response vector and investigate differences in credit card balance between those who own a house and those who don't: $balance = \\beta_0 + \\beta_1Own + \\epsilon$. The categorical variable *Own* can be represented as a vector of 0s and 1s indicating where an individual owns a house. This is also called a dummy variable and takes two possible values: $x_i=1$ if the $i^{th}$ person owns a house and $x_i=0$ otherwise. This results in $y_i = \\beta_0 + \\beta_1 +\\epsilon_i$ if person $i$ owns a house and in $y_i = \\beta_0 +\\epsilon_i$ if person $i$ does not own a house. $\\beta_0$ is now interpreted as the average credit balance for those who do not own, $\\beta_0+\\beta_1$ the average credit balance for those who do own, and $\\beta_1$ reflects the average difference in credit balance between home owners and non-owners. What is the average credit card debt for home owners in the Credit data set?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## fit\nlm(Balance ~ Own, data = Credit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Balance ~ Own, data = Credit)\n\nCoefficients:\n(Intercept)       OwnYes  \n     509.80        19.73  \n```\n\n\n:::\n:::\n\n\n\n::: {.callout-note appearance=\"simple\" icon=false}\n## Task\nUse the `model.matrix()` function to see what the predictor matrix looks like. What do you see?\n:::\n\n::: {.callout-note appearance=\"simple\" icon=false}\n## Task\nExamine the Credit data set. Which columns represent categorical variables? Pick one categorical variable and do a linear fit. Notice that categorical variables are represented as l-1 dummy variables, where l is the number of levels.\n:::\n\nExample:\n\n::: {.cell}\n\n```{.r .cell-code}\nX <- model.matrix(~ Region, \n                  data = Credit)\nhead(X)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept) RegionSouth RegionWest\n1           1           1          0\n2           1           0          1\n3           1           0          1\n4           1           0          1\n5           1           1          0\n6           1           1          0\n```\n\n\n:::\n:::\n\n\nCan you think of another way to represent categorical variables?\n\n\n## Robust regression\n\nSo far in the linear fit, the coefficients are estimated using the least squares methods by minimizing the sum of squared residuals: $\\min\\limits_{\\beta}\\sum_{i=1}^{N}e_{i}^{2}$ where the residual for the $i^{th}$ observation $e_{i} = (y_i - \\hat{y_i})$. What if we had outlier points which would result in large residuals? Does this have an impact on the linear fit? To illustrate this, we will add artificial observations to the advertising data set which deviate quite a bit from the rest of the trend in the data and visualize below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## add outlier points\nnOutliers <- 30\nadvertisingOutlData <- rbind(advertisingData, \n                         data.frame(TV = runif(n = nOutliers, min = 50, max = 150), \n                                    radio = runif(n = nOutliers, min = 10, max = 15), \n                                    newspaper = runif(n = nOutliers, min = 10, max = 30), \n                                    sales = runif(n = nOutliers, min = 20, max = 30)))\n\n## visualize\nggplot(advertisingOutlData, aes(x = TV, y = sales)) + \n    geom_point() + \n    theme_bw()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n\n```{.r .cell-code}\n## fit linear model with lm()\nlmFit <- lm(sales ~ TV, data = advertisingOutlData) \n\n## prepare to plot\ndf <- do.call(cbind, list(advertisingOutlData, \n                          residual = lmFit$residuals, \n                          predictedSales = lmFit$fitted.values))\nbeta0lm <- lmFit$coefficients[\"(Intercept)\"]\nbeta1lm <- lmFit$coefficients[\"TV\"]\n\n## plot\nggplot(df, aes(x = TV, y = sales)) + \n    geom_point() +\n    geom_abline(intercept = beta0lm, slope = beta1lm, color = \"firebrick\") + \n    theme_bw() + \n    geom_segment(aes(x = TV, xend = TV, y = sales, yend = predictedSales),\n                 color = \"steelblue\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-15-2.png){width=672}\n:::\n:::\n\n\nWhat do you notice about the fitted line and the residuals?\n\nCurrently, all residuals contribute equally in the summation we are minimizing. With a robust linear regression, the very big residuals can be weighted less and therefore contribute less to the total sum of the squared residuals. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n## robust linear fit\nrobustFit <- rlm(sales ~ TV, data = advertisingOutlData) \nrobustFit\n\n## prepare to plot\ndf <- do.call(cbind, list(advertisingOutlData, \n                          predictedSales = robustFit$fitted.values, \n                          weightedResidual = robustFit$wresid, \n                          weight = robustFit$w))\nbeta0rlm <- robustFit$coefficients[\"(Intercept)\"]\nbeta1rlm <- robustFit$coefficients[\"TV\"]\n\n## plot\nggplot(df, aes(x = TV, y = sales)) + \n    geom_point() +\n    geom_abline(aes(intercept = beta0lm, \n                    slope = beta1lm,\n                    color = \"Linear regression\")) + \n    geom_abline(aes(intercept = beta0rlm, \n                    slope = beta1rlm,\n                    color = \"Robust regression\")) +\n    geom_abline(aes(intercept = beta0, \n                    slope = beta1,\n                    color = \"Original linear regression (without outliers)\")) +\n    scale_color_manual(name = \"Model\", \n                       values = c(\"Linear regression\" = \"firebrick\", \n                                  \"Robust regression\" = \"forestgreen\", \n                                  \"Original linear regression (without outliers)\" = \"steelblue\")) +\n    theme_bw() \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-1.png){width=960}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nrlm(formula = sales ~ TV, data = advertisingOutlData)\nConverged in 8 iterations\n\nCoefficients:\n(Intercept)          TV \n 8.47754797  0.04390298 \n\nDegrees of freedom: 230 total; 228 residual\nScale estimate: 4.05 \n```\n\n\n:::\n:::\n\n\nNote that the fitted line using the robust regression better fits the trend in the non-outlier points and gets closer to the original fit we had on the data before adding the so-called outliers. The robust regression can have useful applications for example in data sets where we are interested in selecting outliers which deviate from an expected trend, and we want to capture a good fit on that trend.\n\nLet's plot the same scatter plot, coloring by the weight each point receives, reflecting its contribution to the sum of the squared residuals. What do you see? Seeing a scatter plot like this, and assuming we are interested in the outlier points in the cloud above the rest of the data, as they seem to be capturing a signal deviating from an expected background trend, how can we select that group in a data-driven manner?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## plot coloring by weight\np1 <- ggplot(df, aes(x = TV, y = sales)) + \n    geom_point(aes(color = weight)) +\n    geom_abline(intercept = beta0rlm, \n                    slope = beta1rlm,\n                    color = \"forestgreen\") +\n    theme_bw() \n\n## naturally define cutoffs for outliers\np2 <- ggplot(df, aes(x = 1 - weight)) + \n    geom_density() + \n    theme_bw() \ndf$selected <- 1 - df$weight > 0.3\n\np3 <- ggplot(df, aes(x = TV, y = sales)) + \n    geom_point(aes(color = selected)) +\n    geom_abline(intercept = beta0rlm, \n                slope = beta1rlm,\n                color = \"forestgreen\") +\n    theme_bw() \n\np1 + p2 + p3\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-1.png){width=1440}\n:::\n:::\n\n\nWe have done this selection very exploratively, to illustrate that it is possible to select outliers in a data-driven way with robust statistical methods and continue with downstream analyses. Note that in these cases we are actually interested in outliers that deviate from an expected technical or background trend and in properly fitting that expected trend.\n\n::: {.callout-note appearance=\"simple\" icon=false}\n## Task\nUsing the credit data set, model the relationship between Income (response) and Age (predictor). We will assume that there is a general trend between both variables and that there are some individuals who deviate from this trend. We wish to reasonably select  these individuals and fit the background trend. \n:::\n\n\n## Note on non-linearities\n\nThe flexibility and power of linear models is not to be underestimated. So far we have used the predictors as they are in our examples. However there is nothing preventing us from using non-linear transformations of these predictors, such as the square root ($\\sqrt{(x)}$), a log transformation ($log2(x)$) or raising it to the power of some number (such as $x^2$ or $x^3$), to mention a few. The relationship between predictors, whatever transformation they may have taken, is still linear in the context of the linear model. Linear models assume a linear relationship between the predictors and the expected value of the response. Using transformed values of the predictors or response does not violate this, merely how we interpret the fit. \n\n## Variance-bias trade off\n\nSo far with the least squares approach, we have estimated beta coefficients such that the residual sum of squares is minimized. This simple approach while powerful, does not always work best in practice on real world data. If we learn the model on one data set, do we get the same coefficients estimated on another data set? Data can inherently vary due to measuring errors for example, and so we can easily end up over-fitting the coefficients in one data set. Additionally, suppose that two predictors are highly correlated with each other but not with the response. If both predictors get equal coefficient values but opposite signs they cancel each other out. In such cases the coefficients can get arbitrarily large without adding much to the RSS. We again suffer at getting good estimates of the beta coefficients and reliably interpreting them. To overcome these problems and estimate beta coefficients that are more robust and representative shrinkage methods have been proposed by imposing a penalty on the size of the beta coefficients. This problem is known as the variance-bias trade off, since the beta estimates will vary less with such imposed penalties at the expense of being slightly more biased since we are deliberately constraining them.\n\n::: {.callout-note appearance=\"simple\" icon=false}\n## Task\nPick one of the two data sets we have explored so far (Advertising or Credit), randomly split the observations into two and then do a linear fit on each subset. Do you get identical beta estimates or do they vary?\n:::\n\n\n## stabsel\n\ntalk about p > n and colinearity with rand lasso\n\n## more\n\nend with honorable mentions like logistic regression, multivariate regression, graphical lasso, GGMs and the beautiful properties there and how lasso is used\n\n\n## References\n\nA lot of this lab was based on chapters bloop and bloop from ISL \n\n## Session\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndate()\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Tue Aug  4 22:02:13 2026\"\nR version 4.6.0 (2026-04-24)\nPlatform: aarch64-apple-darwin23\nRunning under: macOS Sequoia 15.7.7\n\nMatrix products: default\nBLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \nLAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n\nlocale:\n[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8\n\ntime zone: Europe/Stockholm\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n[1] patchwork_1.3.2 ggplot2_4.0.3   glmnet_5.0      Matrix_1.7-6   \n[5] MASS_7.3-65     ISLR2_1.3-2    \n\nloaded via a namespace (and not attached):\n [1] gtable_0.3.6       jsonlite_2.0.0     dplyr_1.2.1        compiler_4.6.0    \n [5] tidyselect_1.2.1   Rcpp_1.1.1-1.1     splines_4.6.0      scales_1.4.0      \n [9] yaml_2.3.12        fastmap_1.2.0      lattice_0.22-9     R6_2.6.1          \n[13] labeling_0.4.3     generics_0.1.4     shape_1.4.6.1      knitr_1.51        \n[17] iterators_1.0.14   htmlwidgets_1.6.4  tibble_3.3.1       pillar_1.11.1     \n[21] RColorBrewer_1.1-3 rlang_1.2.0        xfun_0.57          S7_0.2.2          \n[25] otel_0.2.0         cli_3.6.6          withr_3.0.2        magrittr_2.0.5    \n[29] digest_0.6.39      foreach_1.5.2      grid_4.6.0         rstudioapi_0.18.0 \n[33] lifecycle_1.0.5    vctrs_0.7.3        evaluate_1.0.5     glue_1.8.1        \n[37] farver_2.1.2       codetools_0.2-20   survival_3.8-6     rmarkdown_2.31    \n[41] pkgconfig_2.0.3    tools_4.6.0        htmltools_0.5.9   \n```\n\n\n:::\n:::\n\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}